### ISSUE TITLE
Help on parser

### ISSUE THREAD

**Issue by oscarmh** [MartinKemper/LoRaWAN-Mapper#1]
Hi Martin I followed your nice tutorial, but I´m struggling ojn decoding the data, can you help me ? Thanks in advance

![image](https://user-images.githubusercontent.com/17768352/63855943-e1b1ff80-c9a0-11e9-9179-d26e74375b13.png)

**Comment by ncamilo** [comment]
The same problem...

**Comment by ncamilo** [comment]
Resolved, change the code of Payload Parser to:

var thing = {

    name:msg.payload.dev_id, 
    
    lat:msg.payload.metadata.gateways[0].latitude, 
    
    lon:msg.payload.metadata.gateways[0].longitude,
    
    application:msg.payload.app_id,
    
    counter:msg.payload.counter,
    
    SF:msg.payload.metadata.data_rate,
    
    RSSI_DL:msg.payload.metadata.gateways[0].rssi,
    
    SNR_DL:msg.payload.metadata.gateways[0].snr,
    
}

msg.payload = thing;

return msg;

and the other thinks work well ok...
